--CLIENTES CON DOMINIO
SELECT ES_CLIENTE, TIPO_PERSONA, CORREO_ELECTRONICO
FROM B_PERSONAS
WHERE TIPO_PERSONA = 'F' AND ES_CLIENTE = 'S' 
AND (CORREO_ELECTRONICO LIKE '%hotmail%'
OR CORREO_ELECTRONICO LIKE '%gmail%;

--VENTAS PRIMER SEMESTRE
SELECT ID_VENTA, NUMERO_CUOTA, MONTO_CUOTA, VENCIMIENTO
FROM B_PLAN_PAGO
WHERE VENCIMIENTO BETWEEN '01/01/18' AND '30/06/18'
ORDER BY 1,2 DESC

--CALCULO CON CANTIDAD
SELECT ID, NOMBRE, UNIDAD_MEDIDA, PRECIO, PORC_COMISION, 
('&&CANT' * PRECIO) AS SUB_TOTAL, (PORC_COMISION * &&CANT * PRECIO) AS COMISION
FROM B_ARTICULOS
WHERE STOCK_ACTUAL > 0
ORDER BY PRECIO DESC

--TRES PRIMERAS FILAS DESPUES DE ORDER BY
SELECT NUMERO, MONTO, FECHA_EMISION 
FROM B_RECIBO_DINERO
ORDER BY MONTO DESC
FETCH FIRST 3 ROWS ONLY

--SALDO A ABONAR
SELECT ID_VENTA, NUMERO_CUOTA, MONTO_CUOTA, VENCIMIENTO 
,FECHA_PAGO, SALDO_CUOTA, ((MONTO_CUOTA - SALDO_CUOTA)* 100)/MONTO_CUOTA AS "% A ABONAR"
FROM B_PLAN_PAGO WHERE ID_VENTA = 2
AND FECHA_PAGO IS NOT NULL
ORDER BY SALDO_CUOTA ASC

--SALDO A ABONAR MENOR AL 50%

SELECT ID_VENTA, NUMERO_CUOTA, MONTO_CUOTA, VENCIMIENTO 
,FECHA_PAGO, SALDO_CUOTA, ((MONTO_CUOTA - SALDO_CUOTA)* 100)/MONTO_CUOTA AS "% A ABONAR"
FROM B_PLAN_PAGO WHERE FECHA_PAGO IS NOT NULL
AND SALDO_CUOTA <= (MONTO_CUOTA/2)
ORDER BY SALDO_CUOTA ASC

---Muestre el nombre de las tablas creadas para las prácticas en
-- laboratorio. Use la vista CAT del diccionariode datos.  
SELECT * FROM CAT;
